insert into internet_shop.address (country, city, street, house, apartment) values ('country', 'city', 'street', 'house', 'apartment');
insert into internet_shop.bouquet (name, description) values ('name', 'description');
insert into internet_shop.courier (name, phone) values ('name', 'phone');
insert into internet_shop.flower (name, number) values ('name', 10);
insert into internet_shop.supplier (name, phone, email, address_id) values ('name', 'phone', 'email', 1);
insert into internet_shop.flower_has_bouquet (flower_id, bouquet_id, number) values (1, 1, 10);
insert into internet_shop.flower_has_supplier (flower_id, supplier_id, number, delivery_date) values (1, 1, 10, current_timestamp);
insert into internet_shop.promotional_code (code, description, active) values ('code', 'description', true);
insert into internet_shop.users (username, email, create_time, active, role, phone) values ('username', 'email', current_timestamp, true, 'role', 'phone');
insert into internet_shop.order_repo (username_id, date, courier_id, promotional_codes, bouquet_id, address_id) values (1, current_timestamp, 1, 1, 1, 1);